### ISSUE TITLE
Remove Armor Break Mechanic

### ISSUE THREAD

**Issue by RandomAnimeGamer** [RandomAnimeGamer/gevdll#10]
The current methodology on the Zealot API does not work. Josh says that we can achieve this by setting armor break variables to -1.

**Comment by RandomAnimeGamer** [comment]
DLL Change

**Comment by Nighlin** [comment]
Fixed in commit https://github.com/RandomAnimeGamer/gevdll/commit/68118ae2a5d55613cc00ae0cfd525877e5ee91f8
