### ISSUE TITLE
Add Pointer for System Info, and offsets to be connected to it.

### ISSUE THREAD

**Issue by Nighlin** [RandomAnimeGamer/gevdll#25]
Its located on this address with no offset:
"NSUNS4.exe"+0161B738

After its added in a similar vein to P and S, then I can apply more functions that will be needed for the future.

**Comment by RandomAnimeGamer** [comment]
The above commit is for the purposes of debugging this Issue.

**Comment by RandomAnimeGamer** [comment]
Issue is fixed in commit a3d1f60 and refined in commit 3609b57
